### ISSUE TITLE
Add travis 

### ISSUE THREAD

**Issue by luisherranz** [frontity/now-builder#7]
Add travis with the same default config we use to have in the past. Something like:
```yaml
language: node_js
cache:
  directories:
    - ~/.npm
    - ~/.cache
install:
  - npm ci
node_js:
  - lts/*
after_success:
  - npm run semantic-release
script:
  - npm run test:ci
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
```
